### ISSUE TITLE
ability to change `--config` parameter name

### ISSUE THREAD

**Issue by gsemet** [phha/click_config_file#12]
I want to use click-config-file in a project that already has a `--config` parameter for something else. Is it possible to overwrite your `--config` optionally, for examples `--defaults`, or optionalize completely this parameter (so it won't be added, and can only load the file defined by config_file_name) ?

**Comment by gsemet** [comment]
ok, I am found it :)
```python
@click_config_file.configuration_option('--defaults', config_file_name="myapps.cfg")
```

**Comment by phha** [comment]
I suppose this issue is solved. Closing it.
