### ISSUE TITLE
It searches AppData\Roaming for config file on windows

### ISSUE THREAD

**Issue by taghizad3h** [phha/click_config_file#23]
Hi there,
I have this error:
`Error: Error reading configuration file: [Errno 2] No such file or directory: 'C:\\Users\\...\\AppData\\Roaming\\main.py\\config'`
I am not currently in that directory so why it searches there to find config file?
Thanks

**Comment by phha** [comment]
This is intended behaviour. By default it will search for a config file in click.get_app_dir(). You can override this by setting the path as an option to click_configuration_option(), or by passing the --config option at start.
